#!/usr/bin/env python3
"""
local_dir.py — helpers for VizCode's per-project artifact directory.

Every scan/AI-report run writes caches, history, reports, etc. under
``<project_root>/.vizcode/``. Those are machine-local, regenerable artifacts —
they should never show up in the user's own git changes. So the first time we
create the directory we also drop a self-ignoring ``.gitignore`` (``*``) inside
it, which tells git to ignore the whole directory regardless of whether the
user has added ``.vizcode/`` to their own top-level ignore file.
"""

from pathlib import Path

_DIRNAME = ".vizcode"
_GITIGNORE_BODY = "# Auto-generated by VizCode — ignore all local scan artifacts.\n*\n"


def ensure_local_dir(project_root) -> Path:
    """Create ``<project_root>/.vizcode/`` (if needed) and ensure it self-ignores.

    Returns the directory Path. Safe to call repeatedly — the mkdir and the
    .gitignore write are both idempotent. Never raises: artifact persistence is
    best-effort and must not abort a scan.
    """
    d = Path(project_root) / _DIRNAME
    try:
        d.mkdir(parents=True, exist_ok=True)
        gi = d / ".gitignore"
        if not gi.exists():
            gi.write_text(_GITIGNORE_BODY, encoding="utf-8")
    except Exception:
        pass
    return d
